'''Detour API endpoints.

This module defines the HTTP API for the Detour collision‑avoidance subsystem.
It provides endpoints for triggering analyses, retrieving status/results,
managing maneuver plans, querying satellite detour state, and running manual screening.
The endpoints are documented with OpenAPI metadata (summaries, descriptions) so they appear in the autogenerated Swagger UI available at `/api/docs`.
'''

from typing import Annotated, List, Optional, Any

from fastapi import APIRouter, Depends, Path, Body, HTTPException, status

from app.api.deps import get_current_user, get_audit_service, get_db
from app.core.exceptions import NotFoundError
from app.db.models.detour import DetourManeuverPlan
from app.services.detour.collision_service import CollisionAvoidanceService
from app.services.detour.state_manager import DetourStateManager
from app.schemas.detour import (
    ConjunctionAnalysisResponse,
    ManeuverPlanSchema,
    SatelliteStateSchema,
    ScreeningRequest,
    ManeuverApprovalRequest,
)

from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession

TokenData = Any  # Alias for token data

class ManeuverRejectRequest(BaseModel):
    '''Payload to reject a maneuver plan.'''
    reason: str = Field(..., description='Reason for rejection')

router = APIRouter()

async def get_detour_state_manager(db: AsyncSession = Depends(get_db)) -> DetourStateManager:
    """Provide a DetourStateManager instance for the request."""
    return DetourStateManager(db)

async def get_detour_service(
    db: AsyncSession = Depends(get_db),
    state_manager: DetourStateManager = Depends(get_detour_state_manager),
    audit = Depends(get_audit_service),
) -> CollisionAvoidanceService:
    """Provide the CollisionAvoidanceService used by the endpoints."""
    return CollisionAvoidanceService(db, state_manager, audit)

@router.post('/conjunctions/{conjunction_id}/analyze', response_model=dict, summary='Trigger Conjunction Analysis', description='Triggers the detour pipeline for a specific conjunction event and returns the session identifier.')
async def trigger_conjunction_analysis(
    conjunction_id: str = Path(..., description='Conjunction event identifier'),
    user = Depends(get_current_user),
    service: CollisionAvoidanceService = Depends(get_detour_service),
):
    """Trigger the Detour pipeline for a specific conjunction event.

    Creates a new analysis session for the given conjunction event ID and returns the identifier of the session.

    Returns:
        dict: ``{"session_id": "<uuid>"}`` – The UUID of the newly created Detour analysis session.

    Example:
        >>> response = client.post("/detour/conjunctions/123/analyze")
        >>> response.json()
        {"session_id": "f2c8e7a4-9c12-4d35-a6f9-8b2c1d2e9e5f"}
    """
    session_id = await service.trigger_conjunction_analysis(conjunction_id, user.tenant_id)
    return {'session_id': session_id}

@router.get('/sessions/{session_id}/status', response_model=dict, summary='Get Analysis Status', description='Retrieve the current status of a Detour analysis session.')
async def get_analysis_status(
    session_id: str = Path(..., description='Detour analysis session identifier'),
    user = Depends(get_current_user),
    service: CollisionAvoidanceService = Depends(get_detour_service),
):
    """Return the current status of a Detour analysis session.

    Provides details such as the session identifier, current status (e.g. ``active``, ``completed``), timestamps and any logged events.

    Returns:
        dict: ``{'session_id': str, 'status': str, 'started_at': str, 'completed_at': Optional[str], 'events': List[dict]}``

    Example:
        >>> response = client.get("/detour/sessions/123/status")
        >>> response.json()
        {'session_id': '123', 'status': 'active', 'started_at': '2026-02-16T12:00:00Z', 'completed_at': None, 'events': []}
    """
    return await service.get_analysis_status(session_id)

@router.get('/sessions/{session_id}/results', response_model=dict, summary='Get Analysis Results', description='Retrieve the final results of a completed analysis session.')
async def get_analysis_results(
    session_id: str = Path(..., description='Detour analysis session identifier'),
    user = Depends(get_current_user),
    service: CollisionAvoidanceService = Depends(get_detour_service),
):
    """Retrieve the final results of a completed analysis session.

    Returns the session identifier, final status, and the output data containing the ops brief, maneuver options, risk assessment, and other analysis details.

    Returns:
        dict: ``{'session_id': str, 'status': str, 'output_data': dict}``

    Example:
        >>> response = client.get("/detour/sessions/123/results")
        >>> response.json()
        {'session_id': '123', 'status': 'completed', 'output_data': {...}}
    """
    return await service.get_analysis_results(session_id)

@router.post('/maneuvers/{plan_id}/approve', response_model=ManeuverPlanSchema, summary='Approve Maneuver Plan', description='Approve a proposed maneuver plan.')
async def approve_maneuver_plan(
    plan_id: str = Path(..., description='Maneuver plan identifier'),
    request: Optional[ManeuverApprovalRequest] = Body(None),
    user = Depends(get_current_user),
    service: CollisionAvoidanceService = Depends(get_detour_service),
):
    """Approve a proposed maneuver plan.

    Updates the plan status to ``approved`` and records the approving user.

    Returns:
        ManeuverPlanSchema: The updated maneuver plan with status ``approved``.

    Example:
        >>> response = client.post("/detour/maneuvers/plan123/approve")
        >>> response.json()["status"]
        "approved"
    """
    plan = await service.approve_maneuver_plan(plan_id, user.sub)
    return ManeuverPlanSchema.model_validate(plan)

@router.post('/maneuvers/{plan_id}/reject', response_model=ManeuverPlanSchema, summary='Reject Maneuver Plan', description='Reject a proposed maneuver plan and record the rejection reason.')
async def reject_maneuver_plan(
    plan_id: str = Path(..., description='Maneuver plan identifier'),
    request: ManeuverRejectRequest = Body(...),
    user = Depends(get_current_user),
    service: CollisionAvoidanceService = Depends(get_detour_service),
):
    """Reject a proposed maneuver plan, persisting the rejection reason.

    Updates the plan status to ``rejected`` and stores the rejection reason in the AI recommendation field.

    Returns:
        ManeuverPlanSchema: The updated maneuver plan with status ``rejected``.

    Example:
        >>> response = client.post("/detour/maneuvers/plan123/reject", json={"reason": "Unsafe maneuver"})
        >>> response.json()["status"]
        "rejected"
    """
    plan = await service.reject_maneuver_plan(plan_id, request.reason, user.sub)
    return ManeuverPlanSchema.model_validate(plan)

@router.post('/maneuvers/{plan_id}/execute', response_model=dict, summary='Execute Maneuver Plan', description='Execute an approved maneuver plan (admin only).')
async def execute_maneuver_plan(
    plan_id: str = Path(..., description='Maneuver plan identifier'),
    user = Depends(get_current_user),
    service: CollisionAvoidanceService = Depends(get_detour_service),
):
    """Execute an approved maneuver plan. Admin role required.

    Checks that the authenticated user has an ``admin`` role; otherwise a 403 error is raised. The plan status must be ``approved``; the service will update the plan to ``executed``, record the execution timestamp, and adjust the satellite's fuel and delta‑v budget.

    Returns:
        dict: ``{'plan_id': str, 'status': str, 'executed_at': str}``

    Example:
        >>> response = client.post("/detour/maneuvers/plan123/execute")
        >>> response.json()["status"]
        "executed"
    """
    if 'admin' not in getattr(user, 'roles', []):
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail='Admin role required to execute maneuver')
    return await service.execute_maneuver_plan(plan_id, user.sub)

@router.get('/satellites/{satellite_id}/state', response_model=SatelliteStateSchema, summary='Get Satellite Detour State', description='Fetch the detour‑specific state for a satellite.')
async def get_satellite_state(
    satellite_id: str = Path(..., description='Satellite identifier'),
    user = Depends(get_current_user),
    state_manager: DetourStateManager = Depends(get_detour_state_manager),
):
    """Fetch the detour‑specific state for a satellite.

    Returns the satellite's fuel remaining, delta‑v budget, and timestamps. If no state exists for the given tenant, a NotFoundError is raised.

    Returns:
        SatelliteStateSchema: The current detour state for the satellite.

    Example:
        >>> response = client.get("/detour/satellites/123/state")
        >>> response.json()["fuel_remaining_kg"]
        100.0
    """
    state = await state_manager.get_satellite_state(satellite_id, user.tenant_id)
    if not state:
        raise NotFoundError('DetourSatelliteState', f'{satellite_id}:{user.tenant_id}')
    return SatelliteStateSchema.model_validate(state)

@router.get('/satellites/{satellite_id}/maneuvers', response_model=list[ManeuverPlanSchema], summary='List Maneuver History', description='Return all maneuver plans that affected the given satellite.')
async def list_maneuver_history(
    satellite_id: str = Path(..., description='Satellite identifier'),
    user = Depends(get_current_user),
    state_manager: DetourStateManager = Depends(get_detour_state_manager),
):
    """Return all maneuver plans that affected the given satellite.

    Retrieves the full history of maneuver plans (proposed, approved, rejected, executed) for the specified satellite and tenant.

    Returns:
        List[ManeuverPlanSchema]: List of maneuver plans.

    Example:
        >>> response = client.get("/detour/satellites/123/maneuvers")
        >>> len(response.json())
        3
    """
    plans = await state_manager.get_maneuver_history(satellite_id, user.tenant_id)
    return [ManeuverPlanSchema.model_validate(p) for p in plans]

@router.post('/screening/run', response_model=dict, summary='Run Manual Screening', description='Execute a manual conjunction screening operation.')
async def run_screening(
    request: ScreeningRequest = Body(...),
    user = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Execute a manual conjunction screening operation.

    Runs the screening tool for the specified satellite over the given time window and distance threshold, returning a list of conjunction candidates.

    Returns:
        dict: The raw result from the screening tool, typically containing a list of candidates and metadata.

    Example:
        >>> response = client.post("/detour/screening/run", json={"satellite_id": "sat123", "time_window_hours": 72, "threshold_km": 5.0})
        >>> response.json()["candidates"]
        []
    """
    from app.agents.detour.tools import screen_conjunctions_tool
    result = await screen_conjunctions_tool(
        request.satellite_id,
        request.time_window_hours,
        request.threshold_km,
        db=db,
    )
    return result
