# -*- coding: utf-8 -*-
"""LangGraph state schema for the Detour subsystem.

The :class:`DetourGraphState` ``TypedDict`` defines the shape of the shared
dictionary that is passed between LangGraph nodes.  Each key is required, but
values may be ``None`` when a particular step has not yet produced data.

All type hints are strict and every field is documented so that developers
(and the LLM agents) understand the expected content.
"""

from __future__ import annotations

from typing import TypedDict, List, Dict, Any, Optional

# Import data structures used throughout the Detour pipeline.
# These imports are deliberately absolute (``app.<module>``) to avoid any
# ambiguity when the code runs inside the FastAPI application.
from app.physics.maneuver import SatelliteState, ManeuverOption
from app.physics.screening import ConjunctionCandidate, ConjunctionEvent


class DetourGraphState(TypedDict):
    """TypedDict representing the shared state of a Detour LangGraph pipeline.

    The state dictionary travels through the *scout*, *analyst*, *planner*,
    *safety* and *ops_brief* nodes.  Fields are populated incrementally; a node
    may read fields that were filled by previous nodes and write its own output.
    """

    # ---------------------------------------------------------------------
    # Core identifiers (always present)
    # ---------------------------------------------------------------------
    session_id: str
    """Unique identifier for the entire Detour analysis session.
    This value is generated when the pipeline is started and is used for
    persistence, SSE streams and logging."""

    tenant_id: str
    """Tenant (customer) identifier – enables multi‑tenant isolation."""

    satellite_id: str
    """Identifier of the primary satellite under analysis."""

    conjunction_event_id: str
    """Identifier of the :class:`ConjunctionEvent` that triggered the workflow."""

    # ---------------------------------------------------------------------
    # Data populated by the various pipeline stages
    # ---------------------------------------------------------------------
    satellite_state: Optional[SatelliteState]
    """Current state of the satellite (mass, fuel, Δv budget).  Filled by the
    ``scout`` node after pulling the latest record from the database."""

    conjunction_data: Optional[ConjunctionEvent]
    """Refined conjunction information produced by the ``scout`` node after
    screening and Newton‑Raphson refinement."""

    screening_results: List[ConjunctionCandidate]
    """List of coarse screening candidates produced by ``screen_conjunctions``.
    The list may be empty if no threats are found."""

    risk_assessment: Optional[Dict[str, Any]]
    """Dictionary containing risk metrics such as ``collision_probability`` and
    ``risk_level``.  Populated by the ``analyst`` node."""

    maneuver_options: List[ManeuverOption]
    """Proposed maneuver options generated by the ``planner`` node.  Each entry
    follows the ``ManeuverOption`` dataclass defined in ``physics.maneuver``."""

    safety_review: Optional[Dict[str, Any]]
    """Result of the safety validation performed by the ``safety`` node.  The
    payload typically includes a boolean ``approved`` flag and optional
    ``issues`` list."""

    ops_brief: Optional[Dict[str, Any]]
    """Operational brief generated by the ``ops_brief`` node – a concise summary
    that can be presented to operators or logged for audit purposes."""

    # ---------------------------------------------------------------------
    # Execution metadata
    # ---------------------------------------------------------------------
    current_agent: str
    """Name of the agent (graph node) that is currently active.  Useful for
    debugging and for informing the frontend about pipeline progress."""

    events: List[Dict[str, Any]]
    """Accumulated events emitted by nodes, formatted for Server‑Sent Events
    (SSE) streams.  Each event dictionary contains at least a ``type`` field and
    a ``payload`` field with node‑specific data."""

    errors: List[str]
    """Error messages collected during execution.  Nodes append their own error
    strings; the API layer can surface them to the client if the pipeline fails.
    """

    completed: bool
    """Flag indicating whether the pipeline has reached a terminal state
    (either successful completion or abort)."""


__all__ = ["DetourGraphState"]
